### ISSUE TITLE
Documentation of Activities for Convention Website

### ISSUE THREAD

**Issue by kimPM** [HBSIph/PPSForceTake3#7]
- [x] Kindly document all activities for Convention Website until Monday, March 5, 2018

**Comment by rpbaguio** [comment]
**PPS Convention website updates as of today (March 5)**
1. Updates of programme and other info (time, venue, and speakers) `[DONE]`
2. UI/UX revisions `[DONE]`
3. Registration & Login `[DONE]` *but still inactive until March 26
4. User dashboard /  Sessions and Abstract page `[DONE]`
5. Feedback form `[DONE]`

**Comment by rpbaguio** [comment]
**WIP**
1. Speaker CV & Abstract file `[IN PROGRESS]`
2. List of participants `[IN PROGRESS]`
3. Admin dashboard `[IN PROGRESS]`

**Comment by kimPM** [comment]
Brod, yung mga susunod na items pa gawan nalang ng separate tickets, including yung mga items na In-Progress. Thanks.

**Comment by rpbaguio** [comment]
New issue?

**Comment by kimPM** [comment]
Yup brod. Thanks.
